# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Docker

name: Lint

variables:
  version: $[counter(variables['build.reason'],0)]
  Tag: 'tremt.diarias.lint'

steps:
  - task: CmdLine@2
    displayName: Executar/Limpar Lint
    inputs:
      script: |
        sudo docker build -f Lint.Dockerfile -t $(Tag):$(version) .
        sudo docker rmi $(Tag):$(version)
