export enum PoliticaValorTransporteEnum {
  VALOR_PASSAGEM_RODOVIARIA = 'VALOR_PASSAGEM_RODOVIARIA',
  VALOR_PASSAGEM_RODOVIARIA_LABEL = 'Valor da passagem rodoviária',
  VALOR_COMBUSTIVEL_PADRAO = 'VALOR_COMBUSTIVEL_PADRAO',
  VALOR_COMBUSTIVEL_PADRAO_LABEL = 'Valor do combustivel padrão',
  SOLIC_ESCOLHE_COMBUSTIVEL_VEICULO = 'SOLIC_ESCOLHE_COMBUSTIVEL_VEICULO',
  SOLIC_ESCOLHE_COMBUSTIVEL_VEICULO_LABEL = 'Solicitante escolhe o combustível do seu veículo'
}
