export enum TipoSolicitacaoEnum {
  VIAGEM_PRE_AUTORIZADA = 'VIAGEM_PRE_AUTORIZADA',
  VIAGEM_PRE_AUTORIZADA_LABEL = 'Viagem pré-autorizada',
  SOLICITACAO_COMPLEMENTAR = 'SOLICITACAO_COMPLEMENTAR',
  SOLICITACAO_COMPLEMENTAR_LABEL = 'Solicitação de Complementação'
}
